# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Header Menu
menu:
  Home: /
  Archives: archives
  Categories: categories
  Tags: tags
  About: about
rss: /atom.xml

since: 2013

# Set default keywords (Use a comma to separate)
keywords: ""

# Put your favicon.ico into `hexo-site/themes/hiero/source/` directory.
favicon: images/favicon.ico

# Put your avatar.jpg into `hexo-site/themes/hiero/source/` directory.
# url is target link (E.g. `url: https://hexo.io/logo.svg` or `url: css/images/mylogo.jpg`)
avatar:
  enable: false
  width: 124
  height: 124
  bottom: 10
  url: https://hexo.io/logo.svg

# AboutPage background
about_big_image:

# Homepage thumbnail
random_thumb: false

# Post Article's Content
post_catalog:
  enable: false

# Sidebar like in homepage, is necessary to disable [post_catalog]
post_sidebar:
  enable: false

# Content
fancybox: true

# Sidebar
sidebar: right
widgets:
  - search
  - social
  - recent_posts
  - category
  - tag
  - tagcloud
  - archive

# Social Links
# Key is the name of FontAwsome icon.
# Value is the target link (E.g. GitHub: https://github.com/iTimeTraveler)
social:
  # Github: https://github.com/iTimeTraveler
  # Weibo: http://www.yoursite.com
  Twitter: https://twitter.com/touzifang
  Telegram: https://t.me/touzifang
  Youtube: https://www.youtube.com/channel/UCMD1mMpbj7ma9Mt1B-5Wm4Q
  # Instagram:
  # Pinterest:
  # Flickr:
  # email:

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search

# Code Highlight theme
# Available value:
#    default | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: default

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: "monthly"
show_count: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification:

# Miscellaneous
twitter: touzifang
fb_admins:
fb_app_id:

# donation button
donate:
  enable: false
  message: "如果觉得我的文章对您有用，请随意打赏。您的支持将鼓励我继续创作!"
  wechatImage: https://raw.githubusercontent.com/iTimeTraveler/iTimeTraveler.github.io/site/source/about/donate/images/WeChanQR.png
  alipayImage: https://raw.githubusercontent.com/iTimeTraveler/iTimeTraveler.github.io/site/source/about/donate/images/AliPayQR.jpg

# Ad
ad:
  google_adsense_ad_client_id: ca-pub-0123456789ABCDEF
